Specify Cohere's model name
cohere-ai/sandbox-toy-semantic-search pull request #3
Opened 2022-11-23 20:33 UTC by AmrMKayid

Right now the cohere model `large` is hard coded. This PR enables specifying which cohere model to use for embeddings the documents and queries

2022-11-23 20:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cohere-ai/sandbox-toy-semantic-search?pullRequest=3) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cohere-ai/sandbox-toy-semantic-search?pullRequest=3) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cohere-ai/sandbox-toy-semantic-search?pullRequest=3) it.</sub>

2022-11-23 20:49 UTC, jcudit approved these changes
nice addition, thanks for making this more flexible!

2022-11-24 09:47 UTC, egrefen requested changes
Thanks for the PR. There is one todo that needs resolving. Beyond that, the suggested changes are superficial.

2022-11-24 09:47 UTC, egrefen commented on embed/cli.py
> +@click.option('--model_name', help='Cohere Model name', default='large')
```suggestion
@click.option('--model_name', help='Cohere model name', default='large')
```

2022-11-24 09:47 UTC, egrefen commented on embed/cli.py
> +@click.option('--model_name', help='Cohere Model name', default='large')
```suggestion
@click.option('--model_name', help='Cohere model name', default='large')
```

2022-11-24 09:47 UTC, egrefen commented on server/app.py
> +    client = SearchClient('/data/embeddings.npz')  # TODO(amr): specify the model name here
Resolve TODO please.

2022-11-24 09:47 UTC, egrefen commented on server/search/cli.py
> +@click.option('--model_name', help='Cohere Model name', default='large')
```suggestion
@click.option('--model_name', help='Cohere model name', default='large')
```

2022-11-24 14:45 UTC, AmrMKayid commented on server/app.py
> +    client = SearchClient('/data/embeddings.npz')  # TODO(amr): specify the model name here
resolved!

2022-11-24 22:35 UTC, egrefen approved these changes
Good to merge after the suggested change is made.

2022-11-24 22:35 UTC, egrefen commented on server/app.py
> +    client = SearchClient('/data/embeddings.npz', model_name=os.environ.get('COHERE_MODEL_NAME', 'large'))
```suggestion
    model_name = os.environ.get('COHERE_MODEL_NAME', 'large')
    client = SearchClient('/data/embeddings.npz', model_name=model_name)
```

2022-11-25 11:10 UTC, merged